# configuration file for psyst

# population synthesis output
pop_synth_database: "example/compas.db"

# flag to check if we want to store COMPAS database as a SQLite file
save_pop_synth_database_as_sql: False
pop_synth_database_sql_name: "compas.db"

# database with summary of MESA models created with the stevdb code
mesa_database: "example/fake.db"

# regular grid of MESA models
mesa_grid_name: "example/complete-grid.yaml"

# interpolation method to use in the matchmaking process
interpolation_method: "weighted_neighbours"

interpolated_results_name: "weighted_neighbours.db"
